import React from 'react';
import Signup from './SignupForm';
import { Metadata } from 'next';
import { redirect } from 'next/navigation';

export const metadata: Metadata = {
  title: 'Register',
  description: 'Generated by create next app',
};

export default function Register() {
  // redirect(`/`);

  return (
    <div>
      <Signup />
    </div>
  );
}
