import React from 'react';
import Signup from './SignupForm';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Register',
  description: 'Generated by create next app',
};

export default function Register() {
  return (
    <div>
      <Signup />
    </div>
  );
}
